"use client";

import {useEffect,useState} from "react";

type Lang="pt"|"en"|"es"|"it"|"he";
const languages:{code:Lang;label:string;short:string}[]=[
  {code:"pt",label:"Português",short:"PT"},{code:"en",label:"English",short:"EN"},
  {code:"es",label:"Español",short:"ES"},{code:"it",label:"Italiano",short:"IT"},
  {code:"he",label:"עברית",short:"HE"},
];
const morro="https://static.wixstatic.com/media/954288_f92ec3cf6dd84a2bb14437d7943de95b~mv2.jpg/v1/fill/w_1200,h_800,al_c,q_85/954288_f92ec3cf6dd84a2bb14437d7943de95b~mv2.jpg";
const sea="https://viagensemenus.com/wp-content/uploads/2022/11/morrodesaopaulo.jpg";
const galleries=[
  ["https://images.elasticrates.com/29/8d/4e/6d/298d4e6d-aa6e-45ef-a175-f33780e71d51/transporte-todoterreno-garapua.jpg?class=details",sea,morro],
  ["/volta-garapua.webp","/volta-morere.webp","/volta-canavieiras.webp","/volta-cairu.webp"],
  ["https://images.elasticrates.com/10/f3/b6/9d/10f3b69d-1668-4d8d-b577-33766e5fa85f/bautismo-buceo-morro-sao-paulo.jpg?aspect_ratio=623%3A354&width=1246",sea,morro],
  ["/quadriciclo-1.webp","/quadriciclo-2.webp","/quadriciclo-3.webp","/quadriciclo-4.webp","/quadriciclo-5.webp"],
  ["/cavalo-1.jpeg","/cavalo-2.jpeg","/cavalo-3.jpeg","/cavalo-4.jpeg","/cavalo-5.jpeg"],
  ["https://static.wixstatic.com/media/954288_f7ffb48215a44fec9a555f344912fc00~mv2.jpg/v1/fill/w_888,h_540,al_c,lg_1,q_85/954288_f7ffb48215a44fec9a555f344912fc00~mv2.jpg",morro,sea],
  ["https://static.wixstatic.com/media/027d48_daf58c52d1f14eb096e25a6486d33bdb~mv2.jpeg/v1/fill/w_1000,h_750,al_c,q_85/027d48_daf58c52d1f14eb096e25a6486d33bdb~mv2.jpeg",sea,morro],
  ["/buggy-1.jpeg","/buggy-2.jpeg","/buggy-3.jpeg", "/buggy-4.jpeg", "/buggy-5.jpeg", "/buggy-6.jpeg"],
  ["/utv-1.jpeg"],               // 8: UTV para Garapuá
  ["/jet-ski-1.jpeg"],           // 9: Jet Ski
  ["/lancha-transparente-1.jpeg"] // 10: Lancha Transparente
];

const modalBackgrounds = [
  "/textures/ondas-garapua.jpeg",   // 0: Garapuá 4x4
  "/textures/ondas-volta-ilha.jpeg", // 1: Volta à Ilha
  "/textures/ondas-mergulho.jpeg",   // 2: Mergulho
  "/textures/ondas-quadri.jpeg",     // 3: Quadriciclo
  "/textures/ondas-cavalo.jpeg",     // 4: Cavalo
  "/textures/ondas-escuna.jpeg",     // 5: Escuna
  "/textures/ondas-gamboa.jpeg",     // 6: Gamboa
  "/textures/ondas-buggy.jpeg",      // 7: Buggy
];


const modalUi={
  pt:{details:"Ver detalhes e fotos",close:"Fechar",previous:"Foto anterior",next:"Próxima foto",photo:"Foto",reserve:"Reservar pelo WhatsApp",itinerary:"Roteiro do dia"},
  en:{details:"View details and photos",close:"Close",previous:"Previous photo",next:"Next photo",photo:"Photo",reserve:"Book on WhatsApp",itinerary:"Day itinerary"},
  es:{details:"Ver detalles y fotos",close:"Cerrar",previous:"Foto anterior",next:"Siguiente foto",photo:"Foto",reserve:"Reservar por WhatsApp",itinerary:"Itinerario del día"},
  it:{details:"Vedi dettagli e foto",close:"Chiudi",previous:"Foto precedente",next:"Foto successiva",photo:"Foto",reserve:"Prenota su WhatsApp",itinerary:"Itinerario della giornata"},
  he:{details:"פרטים ותמונות",close:"סגירה",previous:"תמונה קודמת",next:"התמונה הבאה",photo:"תמונה",reserve:"הזמנה ב-WhatsApp",itinerary:"מסלול היום"},
};
const voltaDetails={
  pt:{intro:"Um dia completo por cinco paradas que unem lazer, gastronomia e história.",time:"Saída a partir das 9h30 · Retorno previsto às 17h30",stops:["Piscinas naturais de Garapuá — primeira parada para banho em águas cristalinas.","Piscinas naturais de Moreré, na Ilha de Boipeba.","Ilha de Boipeba — parada de aproximadamente 2h30 na Praia da Cueira ou Boca da Barra, com tempo livre para conhecer a gastronomia local e almoçar.","Pequeno povoado da ilha, conhecido pelos drinks exóticos com frutas tropicais e pelas ostras frescas.","Cairu — visita ao histórico Convento de Santo Antônio, com sua arquitetura barroca."]},
  en:{intro:"A full day with five stops combining leisure, local food and history.",time:"Departure from 9:30 am · Expected return at 5:30 pm",stops:["Garapuá natural pools — the first stop for a swim in crystal-clear water.","Moreré natural pools on Boipeba Island.","Boipeba Island — approximately 2.5 hours at Cueira Beach or Boca da Barra, with free time to enjoy local cuisine and have lunch.","A small island village known for exotic tropical fruit drinks and fresh oysters.","Cairu — a visit to the historic Santo Antônio Convent and its Baroque architecture."]},
  es:{intro:"Un día completo con cinco paradas de ocio, gastronomía e historia.",time:"Salida a partir de las 9:30 · Regreso previsto a las 17:30",stops:["Piscinas naturales de Garapuá — primera parada para bañarse en aguas cristalinas.","Piscinas naturales de Moreré, en la isla de Boipeba.","Isla de Boipeba — parada de aproximadamente 2 horas y media en Praia da Cueira o Boca da Barra, con tiempo libre para conocer la gastronomía local y almorzar.","Un pequeño pueblo de la isla, conocido por sus bebidas exóticas de frutas tropicales y ostras frescas.","Cairu — visita al histórico Convento de Santo Antônio y su arquitectura barroca."]},
  it:{intro:"Una giornata completa con cinque soste tra relax, gastronomia e storia.",time:"Partenza dalle 9:30 · Rientro previsto alle 17:30",stops:["Piscine naturali di Garapuá — prima sosta per nuotare in acque cristalline.","Piscine naturali di Moreré, sull’isola di Boipeba.","Isola di Boipeba — sosta di circa 2 ore e mezza a Praia da Cueira o Boca da Barra, con tempo libero per scoprire la cucina locale e pranzare.","Un piccolo villaggio dell’isola, noto per i drink esotici alla frutta tropicale e le ostriche fresche.","Cairu — visita allo storico Convento di Santo Antônio e alla sua architettura barocca."]},
  he:{intro:"יום מלא בחמש עצירות המשלבות פנאי, אוכל מקומי והיסטוריה.",time:"יציאה החל מ־9:30 · חזרה משוערת ב־17:30",stops:["הבריכות הטבעיות של גאראפואה — עצירה ראשונה לשחייה במים צלולים.","הבריכות הטבעיות של מוררה באי בויפבה.","האי בויפבה — עצירה של כשעתיים וחצי בחוף קואיירה או בבוקה דה בארה, עם זמן חופשי לארוחה ולהיכרות עם המטבח המקומי.","כפר קטן באי הידוע במשקאות אקזוטיים מפירות טרופיים ובצדפות טריות.","קאירו — ביקור במנזר סנטו אנטוניו ההיסטורי ובאדריכלות הבארוק שלו."]}
};
const quadDetails={
  pt:{intro:"Quinta Praia + Garapuá — um roteiro que combina aventura off-road, natureza, cultura e praias paradisíacas.",time:"Retorno previsto às 16h.",stops:["Saída da Terceira Praia em direção à Quinta Praia, atravessando uma charmosa comunidade e seguindo por uma trilha em meio à mata até a Praia do Encanto.","Na Praia do Encanto, são aproximadamente 3 km de areias brancas e águas cristalinas, com as famosas redes instaladas à beira-mar e dentro da água.","O percurso continua por cerca de 9 km de off-road, passando por mata, restinga e poças d’água até Garapuá, considerada uma das praias mais belas do Brasil.","Em Garapuá, há tempo para aproveitar a gastronomia local, as piscinas naturais, a Igreja de São Francisco e os manguezais de águas cristalinas."]},
  en:{intro:"Fifth Beach + Garapuá — an itinerary combining off-road adventure, nature, culture and idyllic beaches.",time:"Expected return at 4:00 pm.",stops:["Departure from Third Beach towards Fifth Beach, crossing a charming community and following a forest trail to Praia do Encanto.","At Praia do Encanto, enjoy approximately 3 km of white sand and crystal-clear water, including the famous hammocks set by the sea and in the water.","The route continues for about 9 km off-road through forest, coastal vegetation and water crossings to Garapuá, considered one of Brazil’s most beautiful beaches.","In Garapuá, there is time to enjoy local cuisine, the natural pools, São Francisco Church and the crystal-clear mangroves."]},
  es:{intro:"Quinta Playa + Garapuá — un recorrido que combina aventura off-road, naturaleza, cultura y playas paradisíacas.",time:"Regreso previsto a las 16:00.",stops:["Salida desde la Tercera Playa hacia la Quinta Playa, atravesando una encantadora comunidad y siguiendo un sendero entre la vegetación hasta Praia do Encanto.","En Praia do Encanto hay aproximadamente 3 km de arena blanca y aguas cristalinas, con sus famosas hamacas instaladas junto al mar y dentro del agua.","El recorrido continúa durante unos 9 km de off-road, pasando por bosque, restinga y charcos hasta Garapuá, considerada una de las playas más bonitas de Brasil.","En Garapuá hay tiempo para disfrutar de la gastronomía local, las piscinas naturales, la Iglesia de São Francisco y los manglares de aguas cristalinas."]},
  it:{intro:"Quinta Praia + Garapuá — un itinerario che unisce avventura off-road, natura, cultura e spiagge paradisiache.",time:"Rientro previsto alle 16:00.",stops:["Partenza dalla Terza Spiaggia verso Quinta Praia, attraversando una graziosa comunità e seguendo un sentiero nella vegetazione fino a Praia do Encanto.","A Praia do Encanto si trovano circa 3 km di sabbia bianca e acque cristalline, con le famose amache installate sulla riva e dentro l’acqua.","Il percorso prosegue per circa 9 km di off-road tra foresta, restinga e pozze d’acqua fino a Garapuá, considerata una delle spiagge più belle del Brasile.","A Garapuá c’è tempo per scoprire la gastronomia locale, le piscine naturali, la Chiesa di São Francisco e le mangrovie dalle acque cristalline."]},
  he:{intro:"החוף החמישי + גאראפואה — מסלול המשלב הרפתקת שטח, טבע, תרבות וחופים מרהיבים.",time:"חזרה משוערת בשעה 16:00.",stops:["יציאה מהחוף השלישי לכיוון החוף החמישי, דרך קהילה מקסימה ושביל בתוך היער עד לחוף פראיה דו אנקנטו.","בפראיה דו אנקנטו מחכים כ־3 ק״מ של חול לבן ומים צלולים, עם הערסלים המפורסמים שעל שפת הים ובתוך המים.","המסלול ממשיך בכ־9 ק״מ של רכיבת שטח דרך יער, צמחיית חוף ושלוליות עד לגאראפואה, הנחשבת לאחד החופים היפים בברזיל.","בגאראפואה יש זמן ליהנות מהמטבח המקומי, מהבריכות הטבעיות, מכנסיית סאו פרנסיסקו ומיערות המנגרובים בעלי המים הצלולים."]}
};
const copy={
pt:{nav:["Início","Passeios","Quem é a Preta","Translados","Dúvidas"],book:"Falar no WhatsApp",language:"Idioma",heroKicker:"Passeios locais em Morro de São Paulo",heroTitle:"Conheça Morro com quem vive a ilha.",heroText:"Passeios, aventuras e translados organizados de um jeito simples, direto e seguro.",heroCta:"Ver passeios",heroNote:"Atendimento direto com a Preta",sectionKicker:"Experiências em Morro",sectionTitle:"Encontre o passeio certo para sua viagem",sectionText:"Valores informados por pessoa, exceto quando indicado. Consulte a disponibilidade para a data da sua viagem.",from:"A partir de",consult:"Consultar disponibilidade",tours:[
  ["Garapuá de 4×4","Garapuá e Praia do Encanto em um dia de aventura e natureza.","Aventura","R$ 130 por pessoa"],
  ["Passeio Volta à Ilha","Cinco paradas incríveis entre piscinas naturais, praias, gastronomia e história.","Lancha","R$ 350 por pessoa"],
  ["Mergulho com cilindro","Aula teórica, prática acompanhada e fotos inclusas.","Mergulho","R$ 280 por pessoa"],
  ["Quadriciclo: Quinta Praia + Garapuá","Praia do Encanto, trilha off-road e Garapuá em uma experiência completa.","Aventura","R$ 700 por quadriciclo"],
  ["Passeio a cavalo","Passeio a cavalo com duração a partir de duas horas, sempre acompanhado por guia. Você pode escolher entre dois roteiros: uma trilha pela mata ou um percurso pela praia. As saídas acontecem em três opções de horário, sujeitas à disponibilidade. Consulte-nos pelo WhatsApp para verificar os horários e escolher o roteiro ideal.","Natureza","R$ 180 por hora"],
  ["Escuna: Gamboa e Argila","Passeio de escuna com parada em Gamboa e na praia da argila.","Escuna","R$ 100 por pessoa"],
  ["Gamboa Full Experience","Uma experiência completa para aproveitar Gamboa sem pressa.","Experiência","R$ 260 por pessoa"],
  ["Buggy para Garapuá","Um roteiro de aventura por mata preservada, entre trechos de areia e poças d’água, cercado por bromélias, orquídeas silvestres e piaçava. O passeio inclui paradas na Praia de Garapuá e na Praia do Encanto.","Aventura","Consultar pelo WhatsApp"],
  ["UTV para Garapuá", "Aventura incrível pilotando UTV rumo à Praia de Garapuá.", "Aventura", "Consultar pelo WhatsApp"],
  ["Passeio de Jet Ski", "Aproveite a liberdade e adrenalina nas águas de Morro de São Paulo.", "Aventura", "Consultar pelo WhatsApp"],
  ["Lancha Transparente", "Passeio exclusivo para tirar fotos incríveis e ver o fundo do mar.", "Experiência", "Consultar pelo WhatsApp"],
],aboutKicker:"Quem é a Preta",aboutTitle:"Atendimento humano, direto e sem complicação.",aboutText:"A Preta acompanha você desde a escolha do passeio até a confirmação dos detalhes. O atendimento é feito pelo WhatsApp, com informações claras e orientação local para organizar sua experiência em Morro de São Paulo.",features:[["Contato direto","Converse com a Preta pelo WhatsApp antes de reservar."],["Conhecimento da ilha","Orientações sobre praias, marés, passeios e deslocamentos."],["Tudo em um só lugar","Passeios e translados organizados para facilitar sua chegada."]],transferKicker:"Como chegar",transferTitle:"Translados para Morro de São Paulo",transferText:"Consulte horários e valores para a sua data.",transfers:["Catamarã","Semiterrestre","Lancha privativa"],transferCta:"Consultar translado",finalTitle:"Pronto para conhecer Morro?",finalText:"Conte sua data, o número de pessoas e o passeio que mais gostou.",finalCta:"Conversar com a Preta",instagram:"Acompanhar no Instagram",footer:"Turismo local em Morro de São Paulo, Bahia.",popular:"Mais procurado",paymentKicker:"Reserva simples",paymentTitle:"Formas de pagamento",paymentMethods:["Cartão de débito ou crédito","Pix","Dinheiro"],paymentNote:"Valores, disponibilidade e condições podem ser confirmados pelo WhatsApp.",faqKicker:"Antes de reservar",faqTitle:"Dúvidas frequentes",faqText:"Informações gerais para ajudar no planejamento. Confirme os detalhes do seu passeio pelo WhatsApp.",faqs:[["Quais são as formas de pagamento?","Aceitamos cartão de débito ou crédito, Pix e dinheiro."],["Como confirmo a disponibilidade?","A disponibilidade varia conforme a data e o passeio. Confirme pelo WhatsApp antes de se organizar."],["Crianças pagam?","As condições podem variar conforme o passeio e a idade. Confirme pelo WhatsApp."],["O passeio acontece se chover?","A realização depende das condições do tempo e do mar. Confirme pelo WhatsApp no dia ou na véspera."],["Como funciona o cancelamento?","As condições podem variar conforme o passeio e a antecedência. Confirme pelo WhatsApp antes da reserva."]],faqCta:"Confirmar pelo WhatsApp"},
en:{nav:["Home","Tours","Who is Preta","Transfers","FAQ"],book:"Chat on WhatsApp",language:"Language",heroKicker:"Local tours in Morro de São Paulo",heroTitle:"Discover Morro with someone who lives on the island.",heroText:"Tours, adventures and transfers arranged in a simple, direct and reliable way.",heroCta:"View tours",heroNote:"Talk directly to Preta",sectionKicker:"Experiences in Morro",sectionTitle:"Find the right tour for your trip",sectionText:"Prices are per person unless otherwise stated. Please check availability for your travel date.",from:"From",consult:"Check availability",tours:[
  ["Garapuá by 4×4","Garapuá and Praia do Encanto on a day of nature and adventure.","Adventure","R$ 130 per person"],
  ["Around the Island Tour","Five amazing stops featuring natural pools, beaches, local food and history.","Speedboat","R$ 350 per person"],
  ["Scuba diving","Theory lesson, guided practice and photos included.","Diving","R$ 280 per person"],
  ["ATV: Fifth Beach + Garapuá","Praia do Encanto, an off-road trail and Garapuá in one complete experience.","Adventure","R$ 700 per ATV"],
  ["Horseback riding","Guided horseback ride lasting from two hours, with a choice of two routes: a forest trail or a beach route. Departures are available at three different times, subject to availability. Ask us on WhatsApp to confirm the schedules and choose the ideal route.","Nature","R$ 180 per hour"],
  ["Schooner: Gamboa & Clay Beach","A schooner trip with stops in Gamboa and at Clay Beach.","Schooner","R$ 100 per person"],
  ["Gamboa Full Experience","A complete experience to enjoy Gamboa without rushing.","Experience","R$ 260 per person"],
  ["Buggy tour to Garapuá","An adventure route through preserved forest, crossing sandy stretches and water-filled tracks, surrounded by bromeliads, wild orchids and piassava palms. The tour includes stops at Garapuá Beach and Praia do Encanto.","Adventure","Ask on WhatsApp"],
],aboutKicker:"Who is Preta",aboutTitle:"Human, direct and uncomplicated assistance.",aboutText:"Preta supports you from choosing a tour through confirming the details. Assistance happens on WhatsApp, with clear information and local guidance to organize your experience in Morro de São Paulo.",features:[["Direct contact","Chat with Preta on WhatsApp before booking."],["Island knowledge","Advice on beaches, tides, tours and transportation."],["Everything in one place","Tours and transfers arranged to make your arrival easier."]],transferKicker:"Getting here",transferTitle:"Transfers to Morro de São Paulo",transferText:"Ask about schedules and prices for your date.",transfers:["Catamaran","Semi-overland transfer","Private speedboat"],transferCta:"Ask about transfers",finalTitle:"Ready to discover Morro?",finalText:"Tell us your date, group size and which tour you liked most.",finalCta:"Chat with Preta",instagram:"Follow on Instagram",footer:"Local tourism in Morro de São Paulo, Bahia.",popular:"Most popular",paymentKicker:"Simple booking",paymentTitle:"Payment methods",paymentMethods:["Debit or credit card","Pix","Cash"],paymentNote:"Prices, availability and conditions can be confirmed on WhatsApp.",faqKicker:"Before booking",faqTitle:"Frequently asked questions",faqText:"General information to help you plan. Confirm the details of your tour on WhatsApp.",faqs:[["What payment methods are accepted?","We accept debit or credit cards, Pix and cash."],["How do I confirm availability?","Availability varies by date and tour. Please confirm on WhatsApp before making plans."],["Do children pay?","Conditions may vary depending on the tour and the child’s age. Please confirm on WhatsApp."],["Do tours run when it rains?","Tours depend on weather and sea conditions. Please confirm on WhatsApp on the day or the day before."],["What is the cancellation policy?","Conditions may vary according to the tour and how far in advance you cancel. Please confirm on WhatsApp before booking."]],faqCta:"Confirm on WhatsApp"},
es:{nav:["Inicio","Paseos","Quién es Preta","Traslados","Preguntas"],book:"Hablar por WhatsApp",language:"Idioma",heroKicker:"Paseos locales en Morro de São Paulo",heroTitle:"Conoce Morro con quien vive en la isla.",heroText:"Paseos, aventuras y traslados organizados de forma sencilla, directa y segura.",heroCta:"Ver paseos",heroNote:"Atención directa con Preta",sectionKicker:"Experiencias en Morro",sectionTitle:"Encuentra el paseo ideal para tu viaje",sectionText:"Precios por persona, salvo indicación contraria. Consulta la disponibilidad para la fecha de tu viaje.",from:"Desde",consult:"Consultar disponibilidad",tours:[
  ["Garapuá en 4×4","Garapuá y Praia do Encanto en un día de aventura y naturaleza.","Aventura","R$ 130 por persona"],
  ["Paseo Vuelta a la Isla","Cinco paradas increíbles entre piscinas naturales, playas, gastronomía e historia.","Lancha","R$ 350 por persona"],
  ["Buceo con botella","Clase teórica, práctica acompañada y fotos incluidas.","Buceo","R$ 280 por persona"],
  ["Quad: Quinta Playa + Garapuá","Praia do Encanto, ruta off-road y Garapuá en una experiencia completa.","Aventura","R$ 700 por vehículo"],
  ["Paseo a caballo","Paseo a caballo guiado con una duración a partir de dos horas y dos opciones de recorrido: sendero por el bosque o ruta por la playa. Hay salidas en tres horarios diferentes, sujetas a disponibilidad. Consúltanos por WhatsApp para confirmar los horarios y elegir el recorrido ideal.","Naturaleza","R$ 180 por hora"],
  ["Goleta: Gamboa y Arcilla","Paseo en goleta con paradas en Gamboa y la playa de arcilla.","Goleta","R$ 100 por persona"],
  ["Gamboa Full Experience","Una experiencia completa para disfrutar Gamboa sin prisa.","Experiencia","R$ 260 por persona"],
  ["Paseo en buggy a Garapuá","Una ruta de aventura por bosque preservado, entre tramos de arena y charcos, rodeada de bromelias, orquídeas silvestres y palmeras de piaçava. El paseo incluye paradas en la Playa de Garapuá y Praia do Encanto.","Aventura","Consultar por WhatsApp"],
],aboutKicker:"Quién es Preta",aboutTitle:"Atención humana, directa y sin complicaciones.",aboutText:"Preta te acompaña desde la elección del paseo hasta la confirmación de los detalles. La atención se realiza por WhatsApp, con información clara y orientación local para organizar tu experiencia en Morro de São Paulo.",features:[["Contacto directo","Habla con Preta por WhatsApp antes de reservar."],["Conocimiento de la isla","Consejos sobre playas, mareas, paseos y traslados."],["Todo en un solo lugar","Paseos y traslados organizados para facilitar tu llegada."]],transferKicker:"Cómo llegar",transferTitle:"Traslados a Morro de São Paulo",transferText:"Consulta horarios y precios para tu fecha.",transfers:["Catamarán","Traslado semiterrestre","Lancha privada"],transferCta:"Consultar traslado",finalTitle:"¿Listo para conocer Morro?",finalText:"Cuéntanos la fecha, cuántas personas viajan y qué paseo te gustó más.",finalCta:"Hablar con Preta",instagram:"Seguir en Instagram",footer:"Turismo local en Morro de São Paulo, Bahía.",popular:"Más solicitado",paymentKicker:"Reserva sencilla",paymentTitle:"Formas de pago",paymentMethods:["Tarjeta de débito o crédito","Pix","Efectivo"],paymentNote:"Los precios, la disponibilidad y las condiciones se pueden confirmar por WhatsApp.",faqKicker:"Antes de reservar",faqTitle:"Preguntas frecuentes",faqText:"Información general para ayudarte a planificar. Confirma los detalles de tu paseo por WhatsApp.",faqs:[["¿Cuáles son las formas de pago?","Aceptamos tarjeta de débito o crédito, Pix y efectivo."],["¿Cómo confirmo la disponibilidad?","La disponibilidad varía según la fecha y el paseo. Confírmala por WhatsApp antes de organizarte."],["¿Los niños pagan?","Las condiciones pueden variar según el paseo y la edad. Confirma por WhatsApp."],["¿El paseo se realiza si llueve?","La realización depende de las condiciones del tiempo y del mar. Confirma por WhatsApp el mismo día o la víspera."],["¿Cómo funciona la cancelación?","Las condiciones pueden variar según el paseo y la antelación. Confirma por WhatsApp antes de reservar."]],faqCta:"Confirmar por WhatsApp"},
it:{nav:["Home","Escursioni","Chi è Preta","Trasferimenti","Domande"],book:"Contatta su WhatsApp",language:"Lingua",heroKicker:"Escursioni locali a Morro de São Paulo",heroTitle:"Scopri Morro con chi vive sull’isola.",heroText:"Escursioni, avventure e trasferimenti organizzati in modo semplice, diretto e affidabile.",heroCta:"Vedi escursioni",heroNote:"Contatto diretto con Preta",sectionKicker:"Esperienze a Morro",sectionTitle:"Trova l’escursione giusta per il tuo viaggio",sectionText:"Prezzi a persona, salvo diversa indicazione. Verifica la disponibilità per la data del viaggio.",from:"Da",consult:"Verifica disponibilità",tours:[
  ["Garapuá in 4×4","Garapuá e Praia do Encanto in una giornata tra natura e avventura.","Avventura","R$ 130 a persona"],
  ["Escursione giro dell’isola","Cinque splendide soste tra piscine naturali, spiagge, gastronomia e storia.","Motoscafo","R$ 350 a persona"],
  ["Immersione con bombola","Lezione teorica, pratica assistita e foto incluse.","Immersione","R$ 280 a persona"],
  ["Quad: Quinta Praia + Garapuá","Praia do Encanto, percorso off-road e Garapuá in un’esperienza completa.","Avventura","R$ 700 per quad"],
  ["Passeggiata a cavallo","Passeggiata a cavallo guidata della durata di almeno due ore, con due percorsi disponibili: sentiero nella foresta o itinerario sulla spiaggia. Sono previste tre opzioni di partenza, soggette a disponibilità. Contattaci su WhatsApp per confermare gli orari e scegliere il percorso ideale.","Natura","R$ 180 all’ora"],
  ["Goletta: Gamboa e Argilla","Gita in goletta con soste a Gamboa e alla spiaggia dell’argilla.","Goletta","R$ 100 a persona"],
  ["Gamboa Full Experience","Un’esperienza completa per vivere Gamboa senza fretta.","Esperienza","R$ 260 a persona"],
  ["Buggy per Garapuá","Un percorso avventuroso nella foresta preservata, tra tratti sabbiosi e pozzanghere, circondato da bromelie, orchidee selvatiche e palme di piaçava. L’escursione include soste alla spiaggia di Garapuá e a Praia do Encanto.","Avventura","Richiedi su WhatsApp"],
],aboutKicker:"Chi è Preta",aboutTitle:"Assistenza umana, diretta e senza complicazioni.",aboutText:"Preta ti accompagna dalla scelta dell’escursione fino alla conferma dei dettagli. L’assistenza avviene su WhatsApp, con informazioni chiare e indicazioni locali per organizzare la tua esperienza a Morro de São Paulo.",features:[["Contatto diretto","Parla con Preta su WhatsApp prima di prenotare."],["Conoscenza dell’isola","Consigli su spiagge, maree, escursioni e spostamenti."],["Tutto in un unico posto","Escursioni e trasferimenti organizzati per facilitare l’arrivo."]],transferKicker:"Come arrivare",transferTitle:"Trasferimenti per Morro de São Paulo",transferText:"Richiedi orari e prezzi per la tua data.",transfers:["Catamarano","Trasferimento semi-terrestre","Motoscafo privato"],transferCta:"Richiedi trasferimento",finalTitle:"Pronto a scoprire Morro?",finalText:"Indicaci la data, il numero di persone e l’escursione che preferisci.",finalCta:"Parla con Preta",instagram:"Seguici su Instagram",footer:"Turismo locale a Morro de São Paulo, Bahia.",popular:"Più richiesto",paymentKicker:"Prenotazione semplice",paymentTitle:"Metodi di pagamento",paymentMethods:["Carta di debito o credito","Pix","Contanti"],paymentNote:"Prezzi, disponibilità e condizioni possono essere confermati su WhatsApp.",faqKicker:"Prima di prenotare",faqTitle:"Domande frequenti",faqText:"Informazioni generali per aiutarti a pianificare. Conferma i dettagli dell’escursione su WhatsApp.",faqs:[["Quali metodi di pagamento accettate?","Accettiamo carta di debito o credito, Pix e contanti."],["Come posso confermare la disponibilità?","La disponibilità varia in base alla data e all’escursione. Conferma su WhatsApp prima di organizzarti."],["I bambini pagano?","Le condizioni possono variare in base all’escursione e all’età. Conferma su WhatsApp."],["L’escursione si svolge se piove?","Lo svolgimento dipende dalle condizioni meteo e del mare. Conferma su WhatsApp il giorno stesso o il giorno prima."],["Come funziona la cancellazione?","Le condizioni possono variare in base all’escursione e all’anticipo. Conferma su WhatsApp prima di prenotare."]],faqCta:"Conferma su WhatsApp"},
he:{nav:["ראשי","סיורים","מי היא פרטה","העברות","שאלות"],book:"שיחה ב-WhatsApp",language:"שפה",heroKicker:"סיורים מקומיים במורו דה סאו פאולו",heroTitle:"לגלות את מורו עם מי שחיה באי.",heroText:"סיורים, הרפתקאות והעברות המאורגנים בדרך פשוטה, ישירה ואמינה.",heroCta:"לצפייה בסיורים",heroNote:"שירות ישיר עם פרטה",sectionKicker:"חוויות במורו",sectionTitle:"מצאו את הסיור המתאים לטיול שלכם",sectionText:"המחירים הם לאדם, אלא אם צוין אחרת. יש לבדוק זמינות לתאריך הנסיעה.",from:"החל מ-",consult:"בדיקת זמינות",tours:[
  ["גאראפואה ברכב 4×4","גאראפואה ופראיה דו אנקנטו ביום של טבע והרפתקה.","הרפתקה","R$ 130 לאדם"],
  ["סיור מסביב לאי","חמש עצירות נהדרות בין בריכות טבעיות, חופים, אוכל מקומי והיסטוריה.","סירת מנוע","R$ 350 לאדם"],
  ["צלילה עם מכלים","שיעור עיוני, תרגול מודרך ותמונות כלולים.","צלילה","R$ 280 לאדם"],
  ["טרקטורון: החוף החמישי + גאראפואה","פראיה דו אנקנטו, מסלול שטח וגאראפואה בחוויה מלאה.","הרפתקה","R$ 700 לטרקטורון"],
  ["רכיבה על סוסים","טיול רכיבה מודרך הנמשך שעתיים לפחות, עם בחירה בין שני מסלולים: שביל ביער או מסלול לאורך החוף. היציאות מתקיימות בשלוש אפשרויות שעה, בכפוף לזמינות. פנו אלינו ב-WhatsApp כדי לאשר את השעות ולבחור את המסלול המתאים.","טבע","R$ 180 לשעה"],
  ["שיט: גמבואה וחוף החימר","שיט עם עצירות בגמבואה ובחוף החימר.","שיט","R$ 100 לאדם"],
  ["Gamboa Full Experience","חוויה מלאה ליהנות מגמבואה בלי למהר.","חוויה","R$ 260 לאדם"],
  ["טיול באגי לגאראפואה","מסלול הרפתקני דרך יער שמור, בין קטעי חול ושלוליות, מוקף בברומליות, סחלבי בר ודקלי פיאסבה. הסיור כולל עצירות בחוף גאראפואה ובפראיה דו אנקנטו.","הרפתקה","בירור ב-WhatsApp"],
],aboutKicker:"מי היא פרטה",aboutTitle:"שירות אנושי, ישיר ופשוט.",aboutText:"פרטה מלווה אתכם מבחירת הסיור ועד לאישור הפרטים. השירות נעשה ב-WhatsApp, עם מידע ברור והכוונה מקומית לתכנון החוויה במורו דה סאו פאולו.",features:[["קשר ישיר","שוחחו עם פרטה ב-WhatsApp לפני ההזמנה."],["היכרות עם האי","מידע על חופים, גאות ושפל, סיורים ותחבורה."],["הכול במקום אחד","סיורים והעברות המאורגנים כדי להקל על ההגעה."]],transferKicker:"איך מגיעים",transferTitle:"העברות למורו דה סאו פאולו",transferText:"בדקו שעות ומחירים לתאריך שלכם.",transfers:["קטמרן","העברה משולבת יבשה וים","סירת מנוע פרטית"],transferCta:"בירור על העברה",finalTitle:"מוכנים לגלות את מורו?",finalText:"ספרו לנו את התאריך, מספר המטיילים והסיור שאהבתם.",finalCta:"שיחה עם פרטה",instagram:"לעקוב באינסטגרם",footer:"תיירות מקומית במורו דה סאו פאולו, באהיה.",popular:"הכי מבוקש",paymentKicker:"הזמנה פשוטה",paymentTitle:"אמצעי תשלום",paymentMethods:["כרטיס חיוב או אשראי","Pix","מזומן"],paymentNote:"ניתן לאשר מחירים, זמינות ותנאים ב-WhatsApp.",faqKicker:"לפני ההזמנה",faqTitle:"שאלות נפוצות",faqText:"מידע כללי שיעזור בתכנון. אשרו את פרטי הסיור ב-WhatsApp.",faqs:[["אילו אמצעי תשלום מתקבלים?","אנו מקבלים כרטיס חיוב או אשראי, Pix ומזומן."],["איך מאשרים זמינות?","הזמינות משתנה לפי התאריך והסיור. אשרו ב-WhatsApp לפני התכנון."],["האם ילדים משלמים?","התנאים עשויים להשתנות לפי הסיור והגיל. אשרו ב-WhatsApp."],["האם הסיור מתקיים בגשם?","היציאה תלויה בתנאי מזג האוויר והים. אשרו ב-WhatsApp ביום הסיור או יום לפני."],["מהי מדיניות הביטול?","התנאים עשויים להשתנות לפי הסיור ומועד הביטול. אשרו ב-WhatsApp לפני ההזמנה."]],faqCta:"אישור ב-WhatsApp"}
};

const whatsapp="https://wa.me/557599022012";
const instagram="https://www.instagram.com/pretadoturismo";
const siteDomain="https://passeiodapreta.com";
const serviceCta:Record<Lang,string>={pt:"Ver serviços",en:"View services",es:"Ver servicios",it:"Vedi servizi",he:"לצפייה בשירותים"};
const catalogOrder=[1,3,4,7,0,2,5,6,8,9,10] as const;
const assuranceCopy:Record<Lang,{label:string;items:[string,string][]}>={
  pt:{label:"Informações rápidas",items:[["Atendimento direto","Converse com a Preta pelo WhatsApp."],["Rotas para sua viagem","Catamarã, semiterrestre ou lancha privativa."],["Confirmação simples","Consulte horários, valores e disponibilidade."]]},
  en:{label:"Quick information",items:[["Direct assistance","Talk to Preta on WhatsApp."],["Routes for your trip","Catamaran, semi-overland transfer or private speedboat."],["Simple confirmation","Check schedules, prices and availability."]]},
  es:{label:"Información rápida",items:[["Atención directa","Habla con Preta por WhatsApp."],["Rutas para tu viaje","Catamarán, traslado semiterrestre o lancha privada."],["Confirmación sencilla","Consulta horarios, precios y disponibilidad."]]},
  it:{label:"Informazioni rapide",items:[["Assistenza diretta","Parla con Preta su WhatsApp."],["Soluzioni per il viaggio","Catamarano, trasferimento semi-terrestre o motoscafo privato."],["Conferma semplice","Verifica orari, prezzi e disponibilità."]]},
  he:{label:"מידע מהיר",items:[["שירות ישיר","שוחחו עם פרטה ב-WhatsApp."],["אפשרויות הגעה","קטמרן, העברה משולבת או סירת מנוע פרטית."],["אישור פשוט","בדקו שעות, מחירים וזמינות."]]},
};
const whatsappMessages:Record<Lang,{general:string;transfer:string;faq:string;tourPrefix:string}>={
  pt:{general:"Olá, Preta! Vi o site Passeios da Preta e gostaria de conhecer os passeios disponíveis para a minha data.",transfer:"Olá, Preta! Vi os translados no site e gostaria de confirmar opções, horários e valores.",faq:"Olá, Preta! Vi as dúvidas frequentes no site e gostaria de confirmar uma informação.",tourPrefix:"Olá, Preta! Vi no site o passeio"},
  en:{general:"Hello, Preta! I saw the Passeios da Preta website and would like to know which tours are available for my date.",transfer:"Hello, Preta! I saw the transfer options on the website and would like to confirm schedules and prices.",faq:"Hello, Preta! I read the FAQ on the website and would like to confirm some information.",tourPrefix:"Hello, Preta! I saw this tour on the website and I am interested in"},
  es:{general:"¡Hola, Preta! Vi el sitio Passeios da Preta y me gustaría conocer los paseos disponibles para mi fecha.",transfer:"¡Hola, Preta! Vi los traslados en el sitio y me gustaría confirmar opciones, horarios y precios.",faq:"¡Hola, Preta! Vi las preguntas frecuentes en el sitio y me gustaría confirmar una información.",tourPrefix:"¡Hola, Preta! Vi en el sitio el paseo"},
  it:{general:"Ciao, Preta! Ho visto il sito Passeios da Preta e vorrei conoscere le escursioni disponibili per la mia data.",transfer:"Ciao, Preta! Ho visto i trasferimenti sul sito e vorrei confermare opzioni, orari e prezzi.",faq:"Ciao, Preta! Ho letto le domande frequenti sul sito e vorrei confermare un’informazione.",tourPrefix:"Ciao, Preta! Ho visto sul sito l’escursione"},
  he:{general:"שלום פרטה! ראיתי את האתר Passeios da Preta ואשמח לדעת אילו סיורים זמינים בתאריך שלי.",transfer:"שלום פרטה! ראיתי את אפשרויות ההעברה באתר ואשמח לאשר שעות ומחירים.",faq:"שלום פרטה! קראתי את השאלות הנפוצות באתר ואשמח לאשר מידע נוסף.",tourPrefix:"שלום פרטה! ראיתי באתר את הסיור"}
};

const bonfimRibbons=[
  {tone:"pink",d:"M-70 24 C145 1 315 54 515 29 S825 5 1070 43"},
  {tone:"orange",d:"M-70 47 C145 24 315 77 515 52 S825 28 1070 66"},
  {tone:"blue",d:"M-70 70 C145 47 315 100 515 75 S825 51 1070 89"},
  {tone:"yellow",d:"M-70 93 C145 70 315 123 515 98 S825 74 1070 112"},
  {tone:"lilac",d:"M-70 116 C145 93 315 146 515 121 S825 97 1070 135"},
  {tone:"red",d:"M-70 139 C145 116 315 169 515 144 S825 120 1070 158"},
  {tone:"green",d:"M-70 162 C145 139 315 192 515 167 S825 143 1070 181"},
  {tone:"cyan",d:"M-70 185 C145 162 315 215 515 190 S825 166 1070 204"},
  {tone:"gold",d:"M-70 208 C145 185 315 238 515 213 S825 189 1070 227"},
];
const bonfimText="LEMBRANÇA DO SENHOR DO BONFIM DA BAHIA • LEMBRANÇA DO SENHOR DO BONFIM DA BAHIA • LEMBRANÇA DO SENHOR DO BONFIM DA BAHIA •";
function RibbonCluster({position}:{position:string}){
  return <svg className={`ribbonCluster ${position}`} viewBox="0 0 1000 230" preserveAspectRatio="none" aria-hidden="true" focusable="false">
    {bonfimRibbons.map(ribbon=><path id={`${position}-${ribbon.tone}`} className={ribbon.tone} d={ribbon.d} key={ribbon.tone}/>)}
    {bonfimRibbons.map(ribbon=><text className="ribbonText" dy="3" key={`${ribbon.tone}-text`}><textPath href={`#${position}-${ribbon.tone}`} startOffset="1%" textLength="1010" lengthAdjust="spacing">{bonfimText}</textPath></text>)}
  </svg>;
}

export default function Home(){
  const [lang,setLang]=useState<Lang>("pt");const [activeTour,setActiveTour]=useState<number|null>(null);const [slide,setSlide]=useState(0);const t={...copy[lang],heroCta:serviceCta[lang]};const ui=modalUi[lang];const waText=whatsappMessages[lang];const assurance=assuranceCopy[lang];const rtl=lang==="he";
  useEffect(()=>{document.documentElement.lang=lang==="pt"?"pt-BR":lang;document.documentElement.dir=rtl?"rtl":"ltr"},[lang,rtl]);
  useEffect(()=>{document.body.style.overflow=activeTour===null?"":"hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setActiveTour(null);if(activeTour!==null&&e.key==="ArrowRight")setSlide(s=>(s+1)%galleries[activeTour].length);if(activeTour!==null&&e.key==="ArrowLeft")setSlide(s=>(s-1+galleries[activeTour].length)%galleries[activeTour].length)};window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("keydown",onKey);document.body.style.overflow=""}},[activeTour]);
  const wa=(text:string)=>`${whatsapp}?text=${encodeURIComponent(text)}`;
  const openTour=(index:number)=>{setActiveTour(index);setSlide(0)};
  const details=activeTour===1?voltaDetails[lang]:activeTour===3?quadDetails[lang]:null;
  return <main dir={rtl?"rtl":"ltr"}>
    <div className="topbar"><span>Morro de São Paulo · Bahia</span><span><a href="tel:+557599022012">+55 75 99902-2012</a> · <a href={instagram} target="_blank" rel="noreferrer">Instagram</a></span></div>
    <header className="header"><a className="brand" href="#inicio"><img className="brandLogo" src="/logo-passeios-da-preta.jpeg" alt="Passeios da Preta"/></a><nav>{t.nav.map((item,i)=><a key={item} href={["#inicio","#passeios","#sobre","#translados","#duvidas"][i]}>{item}</a>)}</nav><div className="headerActions"><label className="language"><span>◎</span><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value as Lang)}>{languages.map(l=><option key={l.code} value={l.code}>{l.short} · {l.label}</option>)}</select></label><a className="socialCta" href={instagram} target="_blank" rel="noreferrer">Instagram</a><a className="headerCta" href={wa(waText.general)} target="_blank" rel="noreferrer">{t.book}</a></div></header>
    <section className="hero" id="inicio"><div className="heroShade"/><div className="container heroContent"><p className="kicker">{t.heroKicker}</p><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="heroActions"><a className="button" href="#passeios">{t.heroCta}</a><span>✓ {t.heroNote}</span></div></div></section>
    <section className="tourSection" id="passeios"><RibbonCluster position="ribbonsLeft"/><RibbonCluster position="ribbonsRight"/><RibbonCluster position="ribbonsBottom"/><div className="container"><div className="sectionIntro"><p className="kicker">{t.sectionKicker}</p><h2>{t.sectionTitle}</h2><p>{t.sectionText}</p></div><div className="tourGrid">{catalogOrder.map(i=>{const tour=t.tours[i];return <article className="tourCard" key={tour[0]} onClick={()=>openTour(i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")openTour(i)}} tabIndex={0} role="button" aria-label={`${ui.details}: ${tour[0]}`}><div className="cardImage"><img src={galleries[i][0]} alt={tour[0]}/>{i===1&&<span className="popularBadge">{t.popular}</span>}<span className="photoCount">▣ {galleries[i].length}</span></div><div className="cardBody"><span className="category">{tour[2]}</span><h3>{tour[0]}</h3><p>{tour[1]}</p><div className="price">{tour[3].startsWith("R$")&&<small>{t.from}</small>}<strong>{tour[3]}</strong></div><button className="cardLink" type="button">{ui.details} <span>→</span></button></div></article>})}</div></div></section>
    <section className="paymentBand"><div className="container paymentInner"><div><p className="kicker">{t.paymentKicker}</p><h2>{t.paymentTitle}</h2></div><div className="paymentMethods">{t.paymentMethods.map(method=><span key={method}>{method}</span>)}</div><p>{t.paymentNote}</p></div></section>
    <section className="about" id="sobre"><div className="aboutImage"><img src="https://upload.wikimedia.org/wikipedia/commons/5/58/Farol_do_Morro_de_S%C3%A3o_Paulo.jpg" alt="Morro de São Paulo"/></div><div className="aboutCopy"><p className="kicker">{t.aboutKicker}</p><h2>{t.aboutTitle}</h2><p className="aboutText">{t.aboutText}</p><div className="featureList">{t.features.map((f,i)=><div key={f[0]}><span>0{i+1}</span><div><h3>{f[0]}</h3><p>{f[1]}</p></div></div>)}</div></div></section>
    <section className="transfers" id="translados"><div className="container transferGrid"><div><p className="kicker">{t.transferKicker}</p><h2>{t.transferTitle}</h2><p>{t.transferText}</p></div><div className="transferList">{t.transfers.map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong></div>)}</div><div style={{ display: "flex", gap: "10px", flexWrap: "wrap" }}>
  <a className="outlineButton" href={wa(waText.transfer)} target="_blank" rel="noreferrer">{t.transferCta}</a>
  <a className="outlineButton" href="/transfers">Ver todos os translados →</a>
</div></div></section>
    <section className="assuranceBand" aria-label={assurance.label}><div className="container assuranceGrid">{assurance.items.map(([title,text],i)=><div className="assuranceItem" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
    <section className="faqSection" id="duvidas"><div className="container faqGrid"><div className="faqIntro"><p className="kicker">{t.faqKicker}</p><h2>{t.faqTitle}</h2><p>{t.faqText}</p><a className="outlineButton" href={wa(waText.faq)} target="_blank" rel="noreferrer">{t.faqCta}</a></div><div className="faqList">{t.faqs.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="finalCta"><div><h2>{t.finalTitle}</h2><p>{t.finalText}</p></div><div><a className="button" href={wa(waText.general)} target="_blank" rel="noreferrer">{t.finalCta}</a><a className="textLink" href={instagram} target="_blank" rel="noreferrer">{t.instagram} →</a></div></section>
    <footer><a className="brand" href="#inicio"><img className="brandLogo" src="/logo-passeios-da-preta.jpeg" alt="Passeios da Preta"/></a><p>{t.footer}</p><p><a href={siteDomain}>passeiodapreta.com</a></p><p><a href="tel:+557599022012">+55 75 99902-2012</a></p></footer>
    {activeTour!==null&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setActiveTour(null)}} role="presentation"><section className={`tourModal ${details?"detailed":""} ${activeTour===4||activeTour===7?"portraitPhotos":""}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modalClose" onClick={()=>setActiveTour(null)} aria-label={ui.close}>×</button><div className="gallery"><img src={galleries[activeTour][slide]} alt={`${t.tours[activeTour][0]} — ${ui.photo} ${slide+1}`}/><button className="galleryArrow previous" onClick={()=>setSlide(s=>(s-1+galleries[activeTour].length)%galleries[activeTour].length)} aria-label={ui.previous}>‹</button><button className="galleryArrow next" onClick={()=>setSlide(s=>(s+1)%galleries[activeTour].length)} aria-label={ui.next}>›</button><div className="galleryDots">{galleries[activeTour].map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`${ui.photo} ${i+1}`}/>)}</div><span className="galleryCounter">{slide+1} / {galleries[activeTour].length}</span></div><div className="modalContent"><span className="category">{t.tours[activeTour][2]}</span><h2 id="modal-title">{t.tours[activeTour][0]}</h2>{details?<><p className="tourIntro">{details.intro}</p><p className="tourTime">{details.time}</p><h3 className="itineraryTitle">{ui.itinerary}</h3><ol className="itinerary">{details.stops.map(stop=><li key={stop}>{stop}</li>)}</ol></>:<p>{t.tours[activeTour][1]}</p>}<div className="modalPrice">{t.tours[activeTour][3].startsWith("R$")&&<small>{t.from}</small>}<strong>{t.tours[activeTour][3]}</strong></div><a className="button" href={wa(`${waText.tourPrefix} ${t.tours[activeTour][0]}.`)} target="_blank" rel="noreferrer">{ui.reserve}</a></div></section></div>}
    <a className="floating" href={wa(waText.general)} target="_blank" rel="noreferrer" aria-label={t.book}>WhatsApp</a>
    <div 
  className={`modalContent ${details ? "detailed" : ""}`}
  style={{
    backgroundImage: activeTour !== null ? `url(${modalBackgrounds[activeTour]})` : undefined,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat"
  }}
></div>
  </main>
}

const tourBackgrouns = [
  "/textures/ondas-cavalo.jpeg" ,
  "/textures/ondas-quadri.jpeg" , 
  "/textures/ondas-volta.jpeg" ,
  "/textures/buggy.jpeg" , 
"/textures/gamboa-full.jpeg"];